[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev'
]

[phases.build]
cmds = []

[start]
cmd = 'bash start.sh'

[variables]
# Prevent nixpacks from auto-running Laravel commands
NIXPACKS_NO_DEFAULT_PHP_CMD = 'true'
