[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev'
]

[phases.build]
cmds = []

[start]
cmd = '(php artisan storage:link 2>/dev/null || true) && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
